name: CloudCanvas QA
values:
  - key: baseUrl
    value: 'https://qa.cloudcanvas.shalev396.com/api'
    enabled: true
    description:
      content: QA API base URL
      type: text/plain
  - key: testAdminEmail
    value: qa-admin@cloudcanvas.test
    enabled: true
  - key: testAdminPassword
    value: qa-admin-password-1234
    enabled: true
  - key: idToken
    value: ''
    enabled: true
  - key: testServiceId
    value: ''
    enabled: true
  - key: testServiceCategory
    value: ''
    enabled: true
  - key: testServiceSlug
    value: ''
    enabled: true
color: 60
